# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-04 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('prn', models.CharField(default=b'2016BTEIT00025', max_length=250, primary_key=True, serialize=False)),
                ('links', models.CharField(default=b'https://www.youtube.com/', max_length=2500)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
