# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-04 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applet', '0003_auto_20190404_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('Id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('prn', models.CharField(default=b'2016BTEIT00025', max_length=250)),
                ('links', models.CharField(default=b'https://www.youtube.com/', max_length=2500)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
