# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-04 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applet', '0006_auto_20190404_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='sr_no',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='urls',
            name='prn',
            field=models.CharField(default=b'2016BTEIT00025', max_length=250),
        ),
    ]
