# Generated by Django 2.2 on 2019-04-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applet', '0007_auto_20190404_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='links',
            field=models.CharField(default='https://www.youtube.com/', max_length=2500),
        ),
        migrations.AlterField(
            model_name='urls',
            name='prn',
            field=models.CharField(default='2016BTEIT00025', max_length=250),
        ),
    ]
